version: '3.8'

services:
  aggregator:
    build: .
    container_name: aggregator_service
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    networks:
      - aggregator-net

  publisher:
    build: .
    container_name: publisher_service
    depends_on:
      - aggregator
    command: python -m src.publisher
    networks:
      - aggregator-net

networks:
  aggregator-net:
    driver: bridge
